// <auto-generated />
namespace AccountManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class changeQuantityUnitAndTranTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeQuantityUnitAndTranTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201707041001358_changeQuantityUnitAndTranTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
